window.QUESTIONS_DATA = {
  categories: [
    {
      id: "spark",
      name: "Spark",
      description: "Chemistry & desire",
      color: "#C4756A",
      bg: "rgba(196, 117, 106, 0.08)",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 3C10 6.5 8 9.5 8 12.5a4 4 0 0 0 8 0C16 9.5 14 6.5 12 3Z"/>
        <path d="M10 14.5c0 1.8.8 3.2 2 4 1.2-.8 2-2.2 2-4"/>
      </svg>`
    },
    {
      id: "drive",
      name: "Drive",
      description: "Ambition & what you're building",
      color: "#5C6E8A",
      bg: "rgba(92, 110, 138, 0.08)",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">
        <path d="M3 20 L9 8 L13 14 L16 10 L21 20 Z"/>
      </svg>`
    },
    {
      id: "world",
      name: "World",
      description: "Curiosity & how you see things",
      color: "#7A9E82",
      bg: "rgba(122, 158, 130, 0.08)",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 4C7 7 6 15 12 20C18 15 17 7 12 4Z"/>
        <line x1="12" y1="4" x2="12" y2="20"/>
        <path d="M6.5 9.5 Q12 11 17.5 9.5"/>
        <path d="M6 14.5 Q12 16 18 14.5"/>
      </svg>`
    },
    {
      id: "core",
      name: "Core",
      description: "Values & who you are",
      color: "#C49A4A",
      bg: "rgba(196, 154, 74, 0.08)",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">
        <polygon points="12,3 20,7.5 20,16.5 12,21 4,16.5 4,7.5"/>
        <polygon points="12,8 16,10.5 16,15.5 12,18 8,15.5 8,10.5"/>
      </svg>`
    },
    {
      id: "lucky",
      name: "I'm Feeling Lucky",
      description: "A mix of everything",
      color: "#8B7EC8",
      bg: "rgba(139, 126, 200, 0.08)",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 2 L14.4 9.6 L22 12 L14.4 14.4 L12 22 L9.6 14.4 L2 12 L9.6 9.6 Z"/>
      </svg>`
    }
  ],

  questions: [

    // ── SPARK ──────────────────────────────────────────────────────────────
    { id: 1,  text: "Rate yourself in bed, 1 to 10. Justify it.", category: "spark", tags: ["intimacy", "desires"] },
    { id: 2,  text: "Which celebrity would you sleep with, no questions asked?", category: "spark", tags: ["attraction", "desires"] },
    { id: 3,  text: "What have you wanted to try in bed but haven't?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 4,  text: "Have you ever had a sex dream about someone you know?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 5,  text: "What's the most public place you've had sex?", category: "spark", tags: ["desires", "adventure"] },
    { id: 6,  text: "What makes you want to sleep with someone immediately?", category: "spark", tags: ["attraction", "desires"] },
    { id: 7,  text: "Who's the most inappropriate person you've ever been attracted to?", category: "spark", tags: ["attraction", "desires"] },
    { id: 8,  text: "What are you like in bed?", category: "spark", tags: ["intimacy", "desires"] },
    { id: 9,  text: "What's your most seductive move?", category: "spark", tags: ["attraction", "intimacy"] },
    { id: 10, text: "Have you ever sent something explicit to the wrong person?", category: "spark", tags: ["intimacy", "mishap"] },
    { id: 11, text: "What's something you've done sexually that surprised you?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 12, text: "What could someone do to get you into bed immediately?", category: "spark", tags: ["attraction", "desires"] },
    { id: 13, text: "What's the most daring thing you've done with someone you just met?", category: "spark", tags: ["adventure", "desires"] },
    { id: 14, text: "What's a line you thought you'd never cross — but did?", category: "spark", tags: ["desires", "vulnerability"] },
    { id: 15, text: "What was your wildest night?", category: "spark", tags: ["desires", "adventure"] },
    { id: 16, text: "What's your body count?", category: "spark", tags: ["intimacy", "history"] },
    { id: 17, text: "Have you ever faked it?", category: "spark", tags: ["intimacy", "honesty"] },
    { id: 18, text: "What's your biggest turn-on?", category: "spark", tags: ["desires", "attraction"] },
    { id: 19, text: "What's your biggest turn-off in bed?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 20, text: "Have you ever had a one-night stand?", category: "spark", tags: ["intimacy", "history"] },
    { id: 21, text: "Have you ever cheated or been cheated on?", category: "spark", tags: ["relationships", "history"] },
    { id: 22, text: "Vanilla or wild — where do you actually land?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 23, text: "What's your biggest insecurity in bed?", category: "spark", tags: ["vulnerability", "intimacy"] },
    { id: 24, text: "Have you ever been caught in a compromising position?", category: "spark", tags: ["adventure", "mishap"] },
    { id: 25, text: "What's the best sex you've ever had — what made it good?", category: "spark", tags: ["intimacy", "desires"] },
    { id: 26, text: "Do you prefer to pursue or be pursued?", category: "spark", tags: ["attraction", "identity"] },
    { id: 27, text: "What would you do if I kissed you right now?", category: "spark", tags: ["attraction", "present"] },
    { id: 28, text: "What's your type, physically?", category: "spark", tags: ["attraction", "desires"] },
    { id: 29, text: "Have you ever kissed someone you shouldn't have?", category: "spark", tags: ["attraction", "history"] },
    { id: 30, text: "What's the most memorable thing someone has said to you in bed?", category: "spark", tags: ["intimacy", "memory"] },

    // ── DRIVE ──────────────────────────────────────────────────────────────
    { id: 20, text: "If you could be good at any profession without having to put in the work to get there, which would you choose?", category: "drive", tags: ["work", "ambition"] },
    { id: 21, text: "What is something you're terrible at but wish you could do well?", category: "drive", tags: ["skills", "growth"] },
    { id: 22, text: "What is the one thing you've made or built that you're most proud of?", category: "drive", tags: ["work", "pride"] },
    { id: 23, text: "What is your biggest work-related accomplishment?", category: "drive", tags: ["work", "pride"] },
    { id: 24, text: "What have you been meaning to do for a long time but haven't yet done? Why haven't you done it?", category: "drive", tags: ["avoidance", "ambition"] },
    { id: 25, text: "If you'd earn $100,000 a year regardless of your job, what would you actually choose to do?", category: "drive", tags: ["work", "meaning"] },
    { id: 26, text: "Have you ever had a genuine epiphany? What was it about, and what sparked it?", category: "drive", tags: ["growth", "beliefs"] },
    { id: 27, text: "What's the hardest decision you've ever made?", category: "drive", tags: ["decisions", "growth"] },
    { id: 28, text: "What is something you never thought you'd be able to do — until you actually did it?", category: "drive", tags: ["growth", "pride"] },
    { id: 29, text: "What's something you've done that you think everyone should do before they die?", category: "drive", tags: ["experience", "meaning"] },
    { id: 30, text: "Are you currently pursuing what actually makes you happy? Why or why not?", category: "drive", tags: ["meaning", "ambition"] },
    { id: 31, text: "What did you know was a mistake the moment you decided to do it — and why did you go through with it anyway?", category: "drive", tags: ["decisions", "regret"] },
    { id: 32, text: "Think of your biggest regret. If you could go back, would you change it?", category: "drive", tags: ["regret", "decisions"] },
    { id: 33, text: "What one small change in your life had a much bigger impact than you anticipated?", category: "drive", tags: ["growth", "decisions"] },
    { id: 34, text: "What experience are you most proud of yourself for making it through?", category: "drive", tags: ["resilience", "pride"] },
    { id: 35, text: "What's the craziest thing you've ever done?", category: "drive", tags: ["adventure", "experience"] },
    { id: 36, text: "What was the best opportunity you ever received?", category: "drive", tags: ["opportunity", "growth"] },
    { id: 37, text: "Have you ever been offered a real opportunity and turned it down? What happened?", category: "drive", tags: ["decisions", "opportunity"] },
    { id: 38, text: "What is something you're inherently bad at, no matter how hard you try?", category: "drive", tags: ["skills", "identity"] },
    { id: 39, text: "What is the biggest mistake you've made that actually turned out alright in the end?", category: "drive", tags: ["mistakes", "growth"] },
    { id: 40, text: "What's the best decision you've ever made?", category: "drive", tags: ["decisions", "pride"] },
    { id: 41, text: "What's something you had to learn the hard way?", category: "drive", tags: ["lessons", "growth"] },
    { id: 42, text: "What's the hardest time of your life, and how did you get through it?", category: "drive", tags: ["resilience", "growth"] },
    { id: 43, text: "What about yourself is completely different from what you were like 10 years ago?", category: "drive", tags: ["growth", "identity"] },
    { id: 44, text: "What's the most dangerous thing you've ever done, and why did you do it?", category: "drive", tags: ["adventure", "risk"] },
    { id: 45, text: "What's something you enjoyed doing but would never do again?", category: "drive", tags: ["experience", "decisions"] },
    { id: 46, text: "What's the best lesson you've learned from a genuinely difficult situation?", category: "drive", tags: ["lessons", "resilience"] },
    { id: 47, text: "What's the coolest project you've ever worked on?", category: "drive", tags: ["work", "pride"] },
    { id: 48, text: "What's a decision that completely changed your life?", category: "drive", tags: ["decisions", "turning-point"] },
    { id: 49, text: "What's the most spontaneous thing you've ever done?", category: "drive", tags: ["adventure", "experience"] },
    { id: 50, text: "What's something you want to accomplish before the year is over?", category: "drive", tags: ["goals", "ambition"] },

    // ── WORLD ──────────────────────────────────────────────────────────────
    { id: 60, text: "If you could use a time machine, would you go back or forward — and where?", category: "world", tags: ["hypothetical", "time"] },
    { id: 61, text: "If you were an inanimate object, what would you be and why?", category: "world", tags: ["hypothetical", "identity"] },
    { id: 62, text: "If you could be any mythical creature, what would you be?", category: "world", tags: ["hypothetical", "creative"] },
    { id: 63, text: "What cliché do you think is complete bullshit? And what cliché actually holds truth?", category: "world", tags: ["beliefs", "opinions"] },
    { id: 64, text: "If you could choose when and how you die, at what age would you go and how would you want it to happen?", category: "world", tags: ["death", "hypothetical"] },
    { id: 65, text: "What character archetype is closest to your personality?", category: "world", tags: ["identity", "creative"] },
    { id: 66, text: "What's the most ordinary-seeming thing you find genuinely fascinating?", category: "world", tags: ["curiosity", "interests"] },
    { id: 67, text: "What scientific or technological advance genuinely blows your mind?", category: "world", tags: ["curiosity", "future"] },
    { id: 68, text: "What's something that gets more interesting the more you learn about it?", category: "world", tags: ["curiosity", "interests"] },
    { id: 69, text: "If you could live in another time period but in the same place you live now, when would it be?", category: "world", tags: ["hypothetical", "history"] },
    { id: 70, text: "Do you have any conspiracy theories? What are they?", category: "world", tags: ["beliefs", "opinions"] },
    { id: 71, text: "What fictional character do you most relate to?", category: "world", tags: ["identity", "creative"] },
    { id: 72, text: "What's your favorite word and why?", category: "world", tags: ["language", "curiosity"] },
    { id: 73, text: "If you could ask your future self one question, what would it be?", category: "world", tags: ["future", "hypothetical"] },
    { id: 74, text: "What would you title your memoir?", category: "world", tags: ["identity", "creative"] },
    { id: 75, text: "If seasons never changed, which would you live in forever?", category: "world", tags: ["hypothetical", "preferences"] },
    { id: 76, text: "If you lived in a medieval village, what would your job be?", category: "world", tags: ["hypothetical", "creative"] },
    { id: 77, text: "What do you know isn't real but badly want to exist?", category: "world", tags: ["curiosity", "desires"] },
    { id: 78, text: "Can you tell me a joke?", category: "world", tags: ["humor", "social"] },
    { id: 79, text: "If you could play any instrument or learn any language in two hours, which would you choose — and what would you do with it?", category: "world", tags: ["skills", "creative"] },
    { id: 80, text: "What, if anything, is too serious to be joked about?", category: "world", tags: ["beliefs", "humor"] },
    { id: 81, text: "What are you most likely to be arrested for?", category: "world", tags: ["humor", "identity"] },
    { id: 82, text: "If you could be any animal, what would you be and why?", category: "world", tags: ["hypothetical", "identity"] },
    { id: 83, text: "What historical event would you most like to have witnessed?", category: "world", tags: ["history", "curiosity"] },
    { id: 84, text: "You're in a horror film. Your only companion is the last person you texted; your only weapon is whatever's closest to your left hand right now. Do you survive?", category: "world", tags: ["humor", "hypothetical"] },
    { id: 85, text: "If you could live in any fictional world, where would it be?", category: "world", tags: ["creative", "hypothetical"] },
    { id: 86, text: "If you could enhance one of your five senses twofold, which would you choose?", category: "world", tags: ["hypothetical", "body"] },
    { id: 87, text: "What's something you love that most people hate?", category: "world", tags: ["preferences", "identity"] },
    { id: 88, text: "What's something you hate that most people love?", category: "world", tags: ["preferences", "identity"] },
    { id: 89, text: "What will always be funny to you, no matter what?", category: "world", tags: ["humor", "preferences"] },
    { id: 90, text: "If you were a superhero, what would be your name, costume, and catchphrase?", category: "world", tags: ["creative", "hypothetical"] },
    { id: 91, text: "What's the most obscure fact you know?", category: "world", tags: ["curiosity", "knowledge"] },
    { id: 92, text: "What subject could you teach a college course on? What would the units be?", category: "world", tags: ["knowledge", "interests"] },
    { id: 93, text: "Have you ever had a recurring dream or nightmare? What was it about?", category: "world", tags: ["subconscious", "memory"] },
    { id: 94, text: "What is something you fantasize about often?", category: "world", tags: ["desires", "future"] },
    { id: 95, text: "What outfit makes you feel invincible?", category: "world", tags: ["identity", "preferences"] },
    { id: 96, text: "How long is your ideal lifespan? Would you want to live to 200? 500?", category: "world", tags: ["death", "hypothetical"] },
    { id: 97, text: "What have you changed your mind about recently?", category: "world", tags: ["beliefs", "growth"] },
    { id: 98, text: "What's your favorite 'struggle meal'?", category: "world", tags: ["food", "humor"] },
    { id: 99, text: "What's the best purchase you've made this year?", category: "world", tags: ["preferences", "money"] },
    { id: 100, text: "What's your go-to karaoke song?", category: "world", tags: ["music", "humor"] },
    { id: 101, text: "What's your comfort movie or TV series — the one you always go back to?", category: "world", tags: ["media", "preferences"] },
    { id: 102, text: "What's something you think everyone should try at least once?", category: "world", tags: ["experience", "recommendations"] },
    { id: 103, text: "What's something you're embarrassed to admit you enjoy?", category: "world", tags: ["humor", "identity"] },
    { id: 104, text: "What do you think happens after we die, if anything?", category: "world", tags: ["death", "beliefs"] },

    // ── CORE ──────────────────────────────────────────────────────────────
    { id: 120, text: "What is the smallest thing you're genuinely grateful for?", category: "core", tags: ["gratitude", "values"] },
    { id: 121, text: "What is the quality you admire most in the person you dislike most?", category: "core", tags: ["relationships", "self-awareness"] },
    { id: 122, text: "What was the most recent thing that made you cry?", category: "core", tags: ["emotions", "vulnerability"] },
    { id: 123, text: "What's the most trivial thing you have a genuinely strong opinion about?", category: "core", tags: ["opinions", "humor"] },
    { id: 124, text: "What single event or decision most affected the rest of your life?", category: "core", tags: ["turning-point", "memory"] },
    { id: 125, text: "What epithet would you want attached to your name — like 'The Wise' or 'The Fearless'?", category: "core", tags: ["identity", "legacy"] },
    { id: 126, text: "What was the best year of your life? The worst?", category: "core", tags: ["memory", "turning-point"] },
    { id: 127, text: "What's something you've experienced that you wish you could feel again for the first time?", category: "core", tags: ["memory", "nostalgia"] },
    { id: 128, text: "Is there something about you that people assume based on your appearance or demeanor — that isn't actually true?", category: "core", tags: ["identity", "perception"] },
    { id: 129, text: "What's the hardest way you've learned an important lesson?", category: "core", tags: ["lessons", "vulnerability"] },
    { id: 130, text: "What's an irrational fear you have — something you're afraid of despite having no real reason to be?", category: "core", tags: ["fear", "vulnerability"] },
    { id: 131, text: "What was the happiest moment of your life so far?", category: "core", tags: ["joy", "memory"] },
    { id: 132, text: "What's one childhood memory you remember especially clearly?", category: "core", tags: ["childhood", "memory"] },
    { id: 133, text: "Is there a song, smell, or place that strongly reminds you of someone specific?", category: "core", tags: ["memory", "relationships"] },
    { id: 134, text: "What's the closest you've ever come to dying?", category: "core", tags: ["fear", "memory"] },
    { id: 135, text: "Do you have a personal mantra? What is it?", category: "core", tags: ["beliefs", "identity"] },
    { id: 136, text: "What's the worst advice you've ever been given?", category: "core", tags: ["relationships", "lessons"] },
    { id: 137, text: "What fact about yourself took you the longest to understand or accept?", category: "core", tags: ["self-awareness", "identity"] },
    { id: 138, text: "What's your least popular or most controversial opinion?", category: "core", tags: ["opinions", "beliefs"] },
    { id: 139, text: "Does anyone else know your deepest secret? Do you ever plan to tell someone?", category: "core", tags: ["secrets", "vulnerability"] },
    { id: 140, text: "Do you believe more in fate, or in a universe governed by chaos and the unknown?", category: "core", tags: ["beliefs", "philosophy"] },
    { id: 141, text: "What's a quirk of yours that very few people know about?", category: "core", tags: ["identity", "secrets"] },
    { id: 142, text: "Are you currently holding a grudge against anyone?", category: "core", tags: ["relationships", "emotions"] },
    { id: 143, text: "What small, everyday thing annoys you to an irrational degree?", category: "core", tags: ["humor", "identity"] },
    { id: 144, text: "What's something you're hypocritical about — something you believe in but can't seem to actually practice?", category: "core", tags: ["self-awareness", "values"] },
    { id: 145, text: "What are some core principles you hold that you'd never give up?", category: "core", tags: ["values", "beliefs"] },
    { id: 146, text: "What's one thing you're genuinely tired of explaining to people?", category: "core", tags: ["identity", "frustration"] },
    { id: 147, text: "What embarrassing memory will be burned into your mind forever?", category: "core", tags: ["memory", "humor"] },
    { id: 148, text: "In what way do you differ most from your parents?", category: "core", tags: ["family", "identity"] },
    { id: 149, text: "What's something that's difficult for you but seems easy for most other people?", category: "core", tags: ["self-awareness", "identity"] },
    { id: 150, text: "What's something that's easy for you but seems hard for most other people?", category: "core", tags: ["skills", "identity"] },
    { id: 151, text: "If you could know either when you'll die or how, which would you choose?", category: "core", tags: ["death", "hypothetical"] },
    { id: 152, text: "What advice do you wish you'd received much earlier?", category: "core", tags: ["lessons", "growth"] },
    { id: 153, text: "What character trait instantly makes you respect someone?", category: "core", tags: ["values", "relationships"] },
    { id: 154, text: "What's an 'everyday evil' you experience regularly — something banal but deeply unfair?", category: "core", tags: ["frustration", "social"] },
    { id: 155, text: "What's the most selfish thing you've ever done?", category: "core", tags: ["self-awareness", "vulnerability"] },
    { id: 156, text: "What's the most selfless thing you've ever done?", category: "core", tags: ["values", "pride"] },
    { id: 157, text: "What's your least favorite question to be asked?", category: "core", tags: ["identity", "humor"] },
    { id: 158, text: "What wouldn't you do for someone you love?", category: "core", tags: ["relationships", "values"] },
    { id: 159, text: "If you died today, what would be your biggest regret?", category: "core", tags: ["regret", "death"] },
    { id: 160, text: "What do you wish was possible that currently isn't?", category: "core", tags: ["desires", "future"] },
    { id: 161, text: "What gives you genuine hope for the future?", category: "core", tags: ["hope", "future"] },
    { id: 162, text: "What do you find yourself thinking about just before you fall asleep?", category: "core", tags: ["subconscious", "inner-life"] },
    { id: 163, text: "What current trend do you find genuinely troubling, and why?", category: "core", tags: ["beliefs", "society"] },
    { id: 164, text: "What are you currently worrying about? What would actually make you stop?", category: "core", tags: ["fear", "inner-life"] },
    { id: 165, text: "What immediately makes you think less of someone?", category: "core", tags: ["values", "social"] },
    { id: 166, text: "What immediately makes you think more highly of someone?", category: "core", tags: ["values", "social"] },
    { id: 167, text: "What social custom do you wish would just end?", category: "core", tags: ["society", "opinions"] },
    { id: 168, text: "What's a compliment you've never forgotten?", category: "core", tags: ["memory", "relationships"] },
    { id: 169, text: "Describe your life philosophy in 10 words or less.", category: "core", tags: ["philosophy", "identity"] },
    { id: 170, text: "What's the smallest hill you would absolutely die on?", category: "core", tags: ["opinions", "humor"] },
    { id: 171, text: "What's your love language?", category: "core", tags: ["relationships", "identity"] },
    { id: 172, text: "What's something you believe that most people around you don't?", category: "core", tags: ["beliefs", "identity"] },
    { id: 173, text: "What's a relationship dealbreaker for you?", category: "core", tags: ["relationships", "values"] },
    { id: 174, text: "Have you ever committed a crime?", category: "core", tags: ["secrets", "humor"] },
    { id: 175, text: "What's your weird family tradition?", category: "core", tags: ["family", "memory"] },
    { id: 176, text: "What's your toxic trait?", category: "core", tags: ["self-awareness", "humor"] },
    { id: 177, text: "Is there something you want to tell someone, but haven't? Why not?", category: "core", tags: ["relationships", "vulnerability"] },
    { id: 178, text: "What do you find yourself thinking about most when you're alone?", category: "core", tags: ["inner-life", "identity"] },
    { id: 179, text: "What is something you know is going to happen, but hasn't yet?", category: "core", tags: ["future", "inner-life"] },
    { id: 180, text: "How are you, really? Not 'fine.' How are you right now, today, at this moment?", category: "core", tags: ["vulnerability", "presence"] }

  ]
};
