window.QUESTIONS_DATA = {
  categories: [
    {
      id: "spark",
      name: "Spark",
      description: "Chemistry & desire",
      color: "#C4756A",
      bg: "rgba(196, 117, 106, 0.08)",
      icon: `<span class="iconify" data-icon="ph:campfire-duotone" data-width="56" data-height="56"></span>`
    },
    {
      id: "drive",
      name: "Drive",
      description: "Ambition & what you're building",
      color: "#5C6E8A",
      bg: "rgba(92, 110, 138, 0.08)",
      icon: `<span class="iconify" data-icon="ph:mountains-duotone" data-width="56" data-height="56"></span>`
    },
    {
      id: "world",
      name: "World",
      description: "Curiosity & how you see things",
      color: "#7A9E82",
      bg: "rgba(122, 158, 130, 0.08)",
      icon: `<span class="iconify" data-icon="ph:compass-rose-duotone" data-width="56" data-height="56"></span>`
    },
    {
      id: "core",
      name: "Core",
      description: "Values & who you are",
      color: "#C49A4A",
      bg: "rgba(196, 154, 74, 0.08)",
      icon: `<span class="iconify" data-icon="ph:diamond-duotone" data-width="56" data-height="56"></span>`
    },
    {
      id: "lucky",
      name: "I'm Feeling Lucky",
      description: "A mix of everything",
      color: "#8B7EC8",
      bg: "rgba(139, 126, 200, 0.08)",
      icon: `<span class="iconify" data-icon="ph:shooting-star-duotone" data-width="56" data-height="56"></span>`
    }
  ],

  questions: [
    { id: 1, text: "Rate yourself in bed, 1 to 10. Justify it.", category: "spark", tags: ["intimacy", "desires"] },
    { id: 2, text: "Which celebrity would you sleep with, no questions asked?", category: "spark", tags: ["attraction", "desires"] },
    { id: 3, text: "What have you wanted to try in bed but haven't?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 4, text: "Have you ever had a sex dream about someone you know?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 5, text: "What's the most public place you've had sex?", category: "spark", tags: ["desires", "adventure"] },
    { id: 7, text: "Who's the most inappropriate person you've ever been attracted to?", category: "spark", tags: ["attraction", "desires"] },
    { id: 8, text: "What are you like in bed?", category: "spark", tags: ["intimacy", "desires"] },
    { id: 10, text: "Have you ever sent something explicit to the wrong person?", category: "spark", tags: ["intimacy", "mishap"] },
    { id: 14, text: "What's a line you thought you'd never cross — but did?", category: "spark", tags: ["desires", "vulnerability"] },
    { id: 17, text: "Have you ever faked it?", category: "spark", tags: ["intimacy", "honesty"] },
    { id: 18, text: "What's your biggest turn-on?", category: "spark", tags: ["desires", "attraction"] },
    { id: 19, text: "What's your biggest turn-off in bed?", category: "spark", tags: ["desires", "intimacy"] },
    { id: 23, text: "What's your biggest insecurity in bed?", category: "spark", tags: ["vulnerability", "intimacy"] },
    { id: 26, text: "Do you prefer to pursue or be pursued?", category: "spark", tags: ["attraction", "identity"] },
    { id: 28, text: "What's your type, physically?", category: "spark", tags: ["attraction", "desires"] },
    { id: 30, text: "What's the most memorable thing someone has said to you in bed?", category: "spark", tags: ["intimacy", "memory"] },
    { id: 20, text: "If you could be good at any profession without having to put in the work to get there, which would you choose?", category: "drive", tags: ["work", "ambition"] },
    { id: 21, text: "What is something you're terrible at but wish you could do well?", category: "drive", tags: ["skills", "growth"] },
    { id: 22, text: "What is the one thing you've made or built that you're most proud of?", category: "drive", tags: ["work", "pride"] },
    { id: 24, text: "What have you been meaning to do for a long time but haven't yet done? Why haven't you done it?", category: "drive", tags: ["avoidance", "ambition"] },
    { id: 29, text: "What's something you've done that you think everyone should do before they die?", category: "drive", tags: ["experience", "meaning"] },
    { id: 32, text: "Think of your biggest regret. If you could go back, would you change it?", category: "drive", tags: ["regret", "decisions"] },
    { id: 34, text: "What experience are you most proud of yourself for making it through?", category: "drive", tags: ["resilience", "pride"] },
    { id: 36, text: "What was the best opportunity you ever received?", category: "drive", tags: ["opportunity", "growth"] },
    { id: 42, text: "What's the hardest time of your life, and how did you get through it?", category: "drive", tags: ["resilience", "growth"] },
    { id: 43, text: "What about yourself is completely different from what you were like 10 years ago?", category: "drive", tags: ["growth", "identity"] },
    { id: 46, text: "What's the best lesson you've learned from a genuinely difficult situation?", category: "drive", tags: ["lessons", "resilience"] },
    { id: 47, text: "What's the coolest project you've ever worked on?", category: "drive", tags: ["work", "pride"] },
    { id: 50, text: "What's something you want to accomplish before the year is over?", category: "drive", tags: ["goals", "ambition"] },
    { id: 51, text: "If you've had more than one job, which job taught you the most?", category: "drive", tags: ["work", "growth"] },
    { id: 52, text: "What do you think 'success' means? How do you define it in your own life?", category: "drive", tags: ["meaning", "values"] },
    { id: 53, text: "What's your biggest accomplishment so far this year?", category: "drive", tags: ["goals", "pride"] },
    { id: 60, text: "If you could use a time machine, would you go back or forward — and where?", category: "world", tags: ["hypothetical", "time"] },
    { id: 62, text: "If you could be any mythical creature, what would you be?", category: "world", tags: ["hypothetical", "creative"] },
    { id: 66, text: "What's the most ordinary-seeming thing you find genuinely fascinating?", category: "world", tags: ["curiosity", "interests"] },
    { id: 67, text: "What scientific or technological advance genuinely blows your mind?", category: "world", tags: ["curiosity", "future"] },
    { id: 68, text: "What's something that gets more interesting the more you learn about it?", category: "world", tags: ["curiosity", "interests"] },
    { id: 69, text: "If you could live in another time period but in the same place you live now, when would it be?", category: "world", tags: ["hypothetical", "history"] },
    { id: 70, text: "Do you have any conspiracy theories? What are they?", category: "world", tags: ["beliefs", "opinions"] },
    { id: 71, text: "What fictional character do you most relate to?", category: "world", tags: ["identity", "creative"] },
    { id: 73, text: "If you could ask your future self one question, what would it be?", category: "world", tags: ["future", "hypothetical"] },
    { id: 74, text: "What would you title your memoir?", category: "world", tags: ["identity", "creative"] },
    { id: 75, text: "If seasons never changed, which would you live in forever?", category: "world", tags: ["hypothetical", "preferences"] },
    { id: 76, text: "If you lived in a medieval village, what would your job be?", category: "world", tags: ["hypothetical", "creative"] },
    { id: 83, text: "What historical event would you most like to have witnessed?", category: "world", tags: ["history", "curiosity"] },
    { id: 85, text: "If you could live in any fictional world, where would it be?", category: "world", tags: ["creative", "hypothetical"] },
    { id: 86, text: "If you could enhance one of your five senses twofold, which would you choose?", category: "world", tags: ["hypothetical", "body"] },
    { id: 87, text: "What's something you love that most people hate?", category: "world", tags: ["preferences", "identity"] },
    { id: 88, text: "What's something you hate that most people love?", category: "world", tags: ["preferences", "identity"] },
    { id: 93, text: "Have you ever had a recurring dream or nightmare? What was it about?", category: "world", tags: ["subconscious", "memory"] },
    { id: 94, text: "What is something you fantasize about often?", category: "world", tags: ["desires", "future"] },
    { id: 95, text: "What outfit makes you feel invincible?", category: "world", tags: ["identity", "preferences"] },
    { id: 97, text: "What have you changed your mind about recently?", category: "world", tags: ["beliefs", "growth"] },
    { id: 98, text: "What's your favorite 'struggle meal'?", category: "world", tags: ["food", "humor"] },
    { id: 99, text: "What's the best purchase you've made this year?", category: "world", tags: ["preferences", "money"] },
    { id: 100, text: "What's your go-to karaoke song?", category: "world", tags: ["music", "humor"] },
    { id: 102, text: "What's something you think everyone should try at least once?", category: "world", tags: ["experience", "recommendations"] },
    { id: 103, text: "What's something you're embarrassed to admit you enjoy?", category: "world", tags: ["humor", "identity"] },
    { id: 105, text: "Who do you call when stuck in a 3rd world prison cell?", category: "world", tags: ["humor", "hypothetical", "relationships"] },
    { id: 106, text: "If you had the power to completely eradicate one disease, which would you choose?", category: "world", tags: ["hypothetical", "values"] },
    { id: 107, text: "What's your favorite article of clothing you own? Where did you get it?", category: "world", tags: ["preferences", "personal"] },
    { id: 108, text: "Freaky Friday: you wake up in someone else's body for a day — who, and what do they get stuck with?", category: "world", tags: ["hypothetical", "humor"] },
    { id: 109, text: "If you could know for certain the answer to any one question, what would that question be?", category: "world", tags: ["curiosity", "hypothetical"] },
    { id: 110, text: "How long do you think you could survive alone in a remote forest with no tools?", category: "world", tags: ["humor", "hypothetical"] },
    { id: 111, text: "What's your favorite place you've ever travelled to?", category: "world", tags: ["travel", "preferences"] },
    { id: 112, text: "If you had a YouTube channel or podcast, what would it be about?", category: "world", tags: ["interests", "identity"] },
    { id: 121, text: "What is the quality you admire most in the person you dislike most?", category: "core", tags: ["relationships", "self-awareness"] },
    { id: 126, text: "What was the best year of your life? The worst?", category: "core", tags: ["memory", "turning-point"] },
    { id: 127, text: "What's something you've experienced that you wish you could feel again for the first time?", category: "core", tags: ["memory", "nostalgia"] },
    { id: 128, text: "Is there something about you that people assume based on your appearance or demeanor — that isn't actually true?", category: "core", tags: ["identity", "perception"] },
    { id: 130, text: "What's an irrational fear you have — something you're afraid of despite having no real reason to be?", category: "core", tags: ["fear", "vulnerability"] },
    { id: 132, text: "What's one childhood memory you remember especially clearly?", category: "core", tags: ["childhood", "memory"] },
    { id: 133, text: "Is there a song, smell, or place that strongly reminds you of someone specific?", category: "core", tags: ["memory", "relationships"] },
    { id: 134, text: "What's the closest you've ever come to dying?", category: "core", tags: ["fear", "memory"] },
    { id: 135, text: "Do you have a personal mantra? What is it?", category: "core", tags: ["beliefs", "identity"] },
    { id: 137, text: "What fact about yourself took you the longest to understand or accept?", category: "core", tags: ["self-awareness", "identity"] },
    { id: 142, text: "Are you currently holding a grudge against anyone?", category: "core", tags: ["relationships", "emotions"] },
    { id: 143, text: "What small, everyday thing annoys you to an irrational degree?", category: "core", tags: ["humor", "identity"] },
    { id: 147, text: "What embarrassing memory will be burned into your mind forever?", category: "core", tags: ["memory", "humor"] },
    { id: 148, text: "In what way do you differ most from your parents?", category: "core", tags: ["family", "identity"] },
    { id: 151, text: "If you could know either when you'll die or how, which would you choose?", category: "core", tags: ["death", "hypothetical"] },
    { id: 152, text: "What advice do you wish you'd received much earlier?", category: "core", tags: ["lessons", "growth"] },
    { id: 159, text: "If you died today, what would be your biggest regret?", category: "core", tags: ["regret", "death"] },
    { id: 168, text: "What's a compliment you've never forgotten?", category: "core", tags: ["memory", "relationships"] },
    { id: 174, text: "Have you ever committed a crime?", category: "core", tags: ["secrets", "humor"] },
    { id: 181, text: "Where do you wish you had grown up?", category: "core", tags: ["identity", "childhood"] },
    { id: 182, text: "If you could change one thing about yourself physically, what would it be?", category: "core", tags: ["identity", "self-awareness"] },
    { id: 183, text: "Think of the best teacher you've ever had. What did they teach, and what made them so special?", category: "core", tags: ["memory", "relationships"] },
    { id: 184, text: "What trait do you admire in others but don't possess yourself?", category: "core", tags: ["self-awareness", "values"] },
    { id: 185, text: "What is a fear you've faced — and how did you face it?", category: "core", tags: ["fear", "vulnerability"] },
    { id: 186, text: "What person you know do you look up to most, and why?", category: "core", tags: ["relationships", "values"] }
  ]
};
